### ISSUE TITLE
CVE-2019-9740

### ISSUE THREAD

**Issue by vandys** [naftaliharris/tauthon#109]
We should patch this urllib vulnerability ASAP.  Anybody working on it yet?

**Comment by stefantalpalaru** [comment]
It's almost 2 years old: https://bugs.python.org/issue30458

**Comment by vandys** [comment]
Wow.  Should we at least trap embedding control chars into a URL?  I guess it'd be prudent in
both urllib and urllib2

**Comment by kkofler** [comment]
Ping? Is anybody still looking into security fixes for Tauthon? I see no commits to master at all since the 2.8.0 release. Is this project still alive?

Moving from Python 2 to Tauthon would make a lot of sense security-wise (even for code that works fine with Python 2.7.x) if Tauthon is actively maintained, but not if the 2.8.0 release was the end.

**Comment by vandys** [comment]
Since this project does sync from the Python 2.x series, this fix should appear presently.  The founder of "Python 2.8" (nee "Tauthon") has stepped back a bit, not sure if the new maintainer is still available. :-(

**Comment by kkofler** [comment]
That'll work for now, assuming the sync actually happens. (The security fix at hand was committed to the upstream 2.7 branch on 2019-05-21. There has been no sync to Tauthon since then.) But it will no longer be something you can rely on after 2019-12-31. Security fixes will actually need to be backported from Python 3.

**Comment by stefantalpalaru** [comment]
> not sure if the new maintainer is still available

I am.

**Comment by arizvisa** [comment]
Should be closed by #118 if you want to patch before it gets re-sync'd.

**Comment by stefantalpalaru** [comment]
Solved.
