### ISSUE TITLE
make uninstall

### ISSUE THREAD

**Issue by sidro** [naftaliharris/tauthon#112]
make uninstall do not exist.
How to remove tauthon after make install ?

**Comment by sidro** [comment]
I removed it in a barbaric mode.
`updatedb
locate tauthon
locate tauthon > remove
cat remove | xargs rm -R`

**Comment by stefantalpalaru** [comment]
There is no "uninstall" target in the Makefile because you're not really supposed to use `make install`. You should package it for your distro and let your distro's package manager keep track of the files.

As a quick and dirty alternative, you can put it all in a newly created dir: `mkdir ../tauthon-install; make DESTDIR="../tauthon-install" altinstall`

**Comment by arizvisa** [comment]
Confirming stefantalpalaru's comment, CPython 2.7 also does not include an uninstall. As such, it's not a typical process to install from the source and instead one should opt to build a package.

Please review https://docs.python.org/2.0/dist/built-dist.html for how to build a package for your distribution.

(I think this issue can be closed.)
