### ISSUE TITLE
Rename this Project

### ISSUE THREAD

**Issue by flying-sheep** [naftaliharris/tauthon#47]
The current name might confuse people into thinking this was an official port, filing bugs on the official bug tracker for it and so on.

There will never be an official Python 2.8, so there should never be something called “Python 2.8” or similar.

@gvanrossum might confirm this if you don't believe my words.

**Comment by flying-sheep** [comment]
I basically just filed an issue for what people in [this thread](https://mail.python.org/pipermail/python-dev/2016-December/146923.html) were saying

**Comment by nirs** [comment]
Cpython maintainers has abandoned python 2 and the community. I don't see an issue with this name.

Maybe python 3 should change its name, as distriburions are planing to ship python3 as python, breaking good python code assuming that python executable can run python code.

**Comment by flying-sheep** [comment]
I’m sorry you feel that way, but this is not, in fact, the truth. Python 3 is just the next version of the language, announced ~10 years ago. All the time, it was clear Python 2 was going to be deprecated and discontinued eventually, just like Python 1, Java 4, and Lua 5.2.

I don’t know what led to the misconception that Python 2 was going to stick around unlike every deprecated version of any language or software ever. There was no abandonment, just a lack of technical debt elimination and weird emotional attachment to some programming language’s old version.

**Comment by yan12125** [comment]
At least this line should be at the first line: ```This is not an official Python release; see PEP 404```, not in the bottom

**Comment by flying-sheep** [comment]
By the way: If this project gets people to port more easily then I’m all for it!

But the PSF owns the name Python, so unless they decide to adopt this project (which very likely won’t happen because of PEP 404), this project can’t keep its name.

**Comment by paul-nechifor** [comment]
Crazy suggestion: rename it to Pythön, Pythøn, or something like that. [The Python Software Foundation has won disputes over the name in the past](http://arstechnica.com/information-technology/2013/03/python-wins-trademark-dispute-rival-stops-calling-itself-python/) and if your project succeeds they will have to make you change the name.

Love the idea, BTW.

**Comment by ncoghlan** [comment]
Firstly, thanks for taking on the task of creating a hybrid superset of Python 2 that incorporates features you find interesting! Allowing folks to vote with their time and energy and create the projects and remixes that they wish existed is exactly the kind of thing that open source licensing is designed to allow.

However, as others have noted above, the PSF does have various policies specifically around the use of the `Python` mark, and the Trademarks Committee are reviewing the question of whether or not the current name of the project is appropriate in that light.

There's precedent for Python subsets and variants using the term as part of a longer name (e.g. MicroPython, Stackless Python), so something like "HybridPython" would be more likely to pass muster than an unqualified "Python".

Alternatively, a name like NorwegianBlue would reference Guido's original inspiration for the name of the language, while completely steering clear of any possible trademark concerns.

**Comment by dw** [comment]
I'm really happy to see a project like this gain a little traction, and I truly hope it succeeds as I'm certainly not the first or hundredth person to think something like it might be a good idea.

For that reason, and since currently it looks like @naftaliharris is the only developer, spending the limited energy available on an unwinnable trademark issue probably would not be wise.

+1 for changing the project name to something distinct, but it would also be great if the installed binaries and libraries maintained the same interface as official Python, since I think renames there would impact the project's usefulness.

**Comment by flying-sheep** [comment]
> it would also be great if the installed binaries and libraries maintained the same interface as official Python

sure, just not `usr/bin/python2.8`

**Comment by gvanrossum** [comment]
Since I was asked: The project's name (and its binary name) need to change. They are misleading. The rest looks acceptable according to Python's license. This is not an endorsement (far from it).

**Comment by tiran** [comment]
Please also change the name of any helper scripts, the name of the shared library/DLL and the include directory. The name of the header file ```Python.h``` can probably stay since it's part of the public API.

* /usr/bin/python
* /usr/bin/python2.8
* /usr/bin/python-config
* /usr/bin/python2.8-config
* /usr/lib/libpython*
* /usr/include/python2.8

**Comment by stefantalpalaru** [comment]
I'll write a Gentoo ebuild for this package, as soon as you settle on a new name for it.

**Comment by dbohdan** [comment]
If you're going to change the project's name, let me suggest some short, Monty Python-themed options.
* Pythonesque (`/usr/bin/pesque`)
* Reunion
* Cleese
* Brian
* Wanda
* Nudge
* Rabbit
* [Brazil](https://en.wikipedia.org/wiki/Brazil_(1985_film))

**Comment by stefantalpalaru** [comment]
How about "py2", taking a hint from "pypy"?

**Comment by giampaolo** [comment]
"py28"?

**Comment by stefantalpalaru** [comment]
Why also freeze the minor version? It's perfectly possible that a 2.9.x will be released at some point.

**Comment by trevyn** [comment]
"p"

**Comment by paul-nechifor** [comment]
Sadly P is taken: http://esolangs.org/wiki/P .

**Comment by trevyn** [comment]
Looks abandoned, site is down and everything.

**Comment by maedoc** [comment]
Since both 2 and 3 features are handled you might consider `six` (I'm aware that's also the name of a compatibility package).

**Comment by naftaliharris** [comment]
I don't mind renaming this project. Any other suggestions for good names? I personally like "Pythonesque (/usr/bin/pesque)" the best so far, thanks @dbohdan! :-)

@VanL, not that I'm necessarily picking that, but would a name like that be acceptable?

**Comment by kirbyfan64** [comment]
Brydge? Since it's"between" 2 and 3...

Ok, I'll leave now.

**Comment by teles** [comment]
Change the name for snake :snake: !

**Comment by nirs** [comment]
Maybe nython for "nython is not official python"? or for "Naftali's Python"?

**Comment by degaart** [comment]
"snek", please name it "snek"!!!!

**Comment by JulienPalard** [comment]
Still Monty Python inspired: pysant, pronounced "peasant"? (Or present you choose).

A what?
A present!
A what???
A present!
A what???
Un cadeau !
Ahhhh, "a present"!

**Comment by dubberx** [comment]
I like @teles name-of-a-snake idea. What about:\

- kraithon  -  blending krait and python (krait, family of snakes, rhymes with "kite")? O

krait? Or bungarus! (also a snake)

**Comment by ojn** [comment]
Just remove the h - Pyton or call it Flying Circus.

**Comment by naftaliharris** [comment]
> Pyton

Heh. I actually mess this up so often that I alias this on my machine to "python": https://github.com/naftaliharris/dotfiles/blob/master/.bashrc#L151

**Comment by ojn** [comment]
As I think about it, Monty would be a cool name...

**Comment by mrabarnett** [comment]
As it's Python 2, how about DuoPython?

**Comment by naftaliharris** [comment]
> As I think about it, Monty would be a cool name...

It's taken, bummer... http://montyscoconut.github.io/

**Comment by ncoghlan** [comment]
@naftaliharris Thanks for being responsive to the name change request!

Assuming it is able to obtain the PSF's blessing from a trademark perspective, @dbohdan's suggestion of Pythonesque (pesque) sounds promising to me, as the main benefit of the project lies in it being Python-like, without being 100% constrained to meeting any specific version of the language definition (in particular, combining syntactic and runtime features of Python 3 with the Python 2 core data model).

**Comment by naftaliharris** [comment]
> Thanks for being responsive to the name change request!

Of course @ncoghlan. :-)

Off topic, but I've just got to say I'm a huge fan of yours. As you'd imagine when working on this I read a *lot* of your code and writing, and have a ton of respect for the work you've done for the Python community over the last 10+ years. You should be very very proud.

**Comment by ntoll** [comment]
May I suggest "Parrot"..?

Why?

1) It's not dead, it's just... etc... (appropriate Monty Python reference).
2) It's still an animal.
3) It's not a Python.

Potential issue: doesn't PERL have a parrot VM? Might be too close...?

**Comment by flying-sheep** [comment]
Yeah, parrot is probably not a good fit for that reason.

Someone suggested using the breed of parrot used in the sketch (Norwegian blue), but that reference might be too obscure.

“pesque” sounds a bit too much like “pesky” IMHO.

**Comment by meiralins** [comment]
I would call it Phyton.

**Comment by pfalcon** [comment]
Given that the project poses itself as an implementation of https://www.python.org/dev/peps/pep-0404/ ("Python 2.8 Un-release Schedule") , a logical name would be "Unpython".

**Comment by ncoghlan** [comment]
Regarding the command name to pair up with the suggestion of "Pythonesque", `pyesque` occurred to me as a potentially clearer option than `pesque` - it has the `py` prefix (suggesting Python), and avoids the similarity to "pesky" that @flying-sheep mentioned.

**Comment by avamsi** [comment]
How about Pythold?

<sup>Okay, I'll get out of here now.</sup>

**Comment by cndreisbach** [comment]
The [wonambi](https://en.wikipedia.org/wiki/Wonambi) is an extinct Australian snake species. While it was not a python, it was a constrictor. The name wonambi refers to the mythological Rainbow Serpent of the Dreamtime. Wonambi(s?) were around 6 meters long, making it a very large and terrifying snake.

Anyway, the name of a extinct constrictor seems pretty appropriate and badass for this resurrection of an extinct Python.

**Comment by naftaliharris** [comment]
Thinking more about this, "py28" has the nice advantage of keeping with the original inspiration for this project and being easy to say ("pie two eight"). I've asked the PSF if that name works for them.

**Comment by gvanrossum** [comment]
Doesn't work for me, sorry.

--Guido (mobile)

**Comment by ncoghlan** [comment]
Regarding `py28`, that wouldn't resolve the confusion, as the `pyXY` abbreviations are used specifically in https://www.python.org/dev/peps/pep-0425/#overview to refer to versions of the language definition, and folks often use them that way in other contexts as well.

Another possibility that occurs to me is to name the project after it's key *difference* from Python 3, which is that it retains the POSIX-style text model that's more suitable for wire encodings and boundary code where the bytes/text boundary is fuzzy than it is normal application development logic (where you're mainly working with text and other forms of structured data): http://python-notes.curiousefficiency.org/en/latest/python3/questions_and_answers.html#what-actually-changed-in-the-text-model-between-python-2-and-python-3

Some name ideas in that vein:

* `pynix`: Python with the \*nix text model
* `pysix`: Python with the POSIX text model (and also a reference to the `six` compatibility project)
* `fuzzypy`: Python with a fuzzily defined `str` type
* `asciipy`: Python with Python 2's old preference for ASCII as the default encoding and its ASCII-based restrictions on identifiers

Of all the suggestions so far, I think that last one wins handily in terms of explaining both:

- why the project exists (there's still a whole lot of software out there that shares Python 2's assumptions about ASCII vs the Unicode-native perspective of Python 3)
- whether or not someone might want to use it (i.e. if assuming ASCII as the default encoding in a lot of places is a behaviour you actually want, then AsciiPy may be a better fit for your needs than Python 3)

**Comment by bcse** [comment]
Since py2, py28 is not acceptable... How about pytwo?

**Comment by tisdall** [comment]
**pynono** - everyone knows extending 2 is a no-no.

**Comment by rsalmaso** [comment]
pydue (due: italian word for 2)

**Comment by stefantalpalaru** [comment]
Disregard Guido's objection. The "Python" trademark doesn't extend to "py2" or "py28". Read this for details: https://www.python.org/psf/trademarks/

**Comment by gvanrossum** [comment]
Isn't the whole point that we're trying to solve this *without* lawyers?

**Comment by stefantalpalaru** [comment]
The whole point is that you've been sabotaging Python 2 for years and when someone does what needed to be done from the start, you come up with silly objections.

**Comment by gvanrossum** [comment]
OK, bring in the lawyers.

**Comment by lordmauve** [comment]
How about "fudge"?

* Fudge tastes nice (happy, positive)
* Doesn't mention Python (keeps PSF happy)
* Descriptive of how it fudges the difference between Python 2 and 3 (cute and self-deprecating)

**Comment by srumbalski** [comment]
Would "NotPython 2.8" be considered infringing?  The 2.8 would be a statement that it is meant to be an extension of the 2.x line, while the NotPython would be a very explicit disclaimer of official blessing.

**Comment by CorbinSimpsonAcquia** [comment]
I'm afraid that "Monte" is taken, making "Monty" very confusing: http://www.monte-language.org/

**Comment by kirbyfan64** [comment]
Well, this went downhill fast. If the dev really wants to stick with 2.8, then I'd say @srumbalski's suggestion of NotPython2.8 (`notpy2.8`?) is a good middle.

**Comment by flying-sheep** [comment]
@srumbalski the problem isn’t any specific word, it’s simply “could someone reading that name think it’s an official python version?”

that has so far been the case for “Python2.8” (obviously) and “py28” (pyXY is a common abbreviation for Python X.Y)

> Well, this went downhill fast

no, everyone here is nice and amicable except for stefantalpalaru, who is hostile, antagonising, and rude. if we just stay in good spirits and forget him, this can stay a nice, positive thread!

**Comment by naftaliharris** [comment]
I'm temporarily renaming this project to "Placeholder" (#52) while we find a good permanent name that I like and that works for the PSF.

**Comment by markhkim** [comment]
Pylaceholder!

**Comment by ncoghlan** [comment]
@naftaliharris Good idea, as that makes it much clearer that the name change discussion is still in progress. Taking a step back, I think it's worth thinking explicitly about *who* the new name aims to benefit.

1. First and foremost, it's for you. It needs to be a name where seeing it in URLs and web pages and emails and local directory names brings a smile to your face. Whether that's Monty Python references, or something literally descriptive, or a play on words, amusing you as the project's creator is an important aspect here.

2. Secondly, it's for Python 2.7 users that are more intrigued by getting otherwise Python 3.x only components working under a Python 2 variant than they are using tools like python-modernize and python-future to bring their own code bases up into the common subset of Python 2 & 3. This is the point of view that pushes against being *too* obscure or vague in the naming (Placeholder, Pyquisition, NorwegianBlue, Pythonesque, etc), but also opens up possibilities like:

  * AsciiPy (emphasising the retention of Python 2's ASCII-centric data model)
  * Pyvergent (referencing both the divergence from upstream Python as well as the convergence between 2 & 3)
  * Pytangent (referencing that where upstream development took a turn in the direction of Unicode-as-default, print as a builtin, and other incompatibilities, this is more a straight line successor of the 2.x series)

3. Finally, it's for folks learning Python and trying to understand not only the Python 2/3 split, but also our wide array of competing interpreter implementations. However, since quite a few of these folks are going to be starting out with Python 3 and then inheriting legacy Python 2 code bases as part of paid software maintenance roles, their needs shouldn't be that different from those in the 2nd category above.

And with that, the last option I'll throw into the mix for now is "Pyfrost", which is one that occurred to me after looking up "Pybridge" (to find it already taken) and rejecting "Pystasis" (as that's a more accurate description of Python 2.7 itself than it is this project):

- the "Pybridge" connection is that "Pyfrost" rhymes with a common English mispronunciation of "Bifrost", the bridge between Midgard and Asgard in Nordic legend (TIL that "Bifrost" is supposed to be pronounced with a long EE sound in the first syllable and rhyming with "roast" rather than "cost")
- the "Pystasis" connection is that where 2.7 is almost entirely frozen, "Pyfrost" would only be frozen against the breaking changes that require code modernisation to get into the common subset of Python 2 & 3

**Comment by mrabarnett** [comment]
Here's another suggestion: IndyPython

The first item 1 on this list explains why:

9 Geekiest Things Named After Monty Python
http://www.thegeektwins.com/2013/09/9-geekiest-things-named-after-monty_5.html

**Comment by flying-sheep** [comment]
that works super well IMHO!

> Scientists named the gene “Indy,” an acronym for “I’m not dead yet”

it also means “independent”, and Indy(ana Jones) is an archeologist, digging up valuable ancient things from dangerous environments!

**Comment by e3krisztian** [comment]
Naming is pretty hard, e.g. `Pythonesque` would immediately make me leave (sorry, I understand, that it might be just me)

I like @ncoghlan's `asciipy` as it highlights the difference and is quite short.

@mrabarnett's `IndyPython` (“I’m not dead yet” Python) is hilarious!
Two variants:
- `Indy`
- `pindy` (with the extra meaning [gone bad](https://www.merriam-webster.com/dictionary/pindy))

or `snek` :)

**Comment by lfairy** [comment]
> Here's another suggestion: IndyPython

That looks too similar to "IronPython" to me.

**Comment by flying-sheep** [comment]
How? for me it doesn’t at all. Just because of the capital “I”?

maybe without CamelCase: `indy_python`

**Comment by henrebotha** [comment]
Omg please make "snek" happen

**Comment by phillipberndt** [comment]
FWIW, @ncoghlan's `pynix` suggestion captures my interest in this project pretty well. *The* key difference between Python 2 and 3 to me is the *philosophical* decision against POSIX that came with Python 3's conceptual transition to regard stdin/argv/file names as text with a well-defined encoding rather than as the byte streams they are in a POSIX world.

**Comment by native-api** [comment]
My vote is for PythonBackport as a "one obvious way".

**Comment by ionelmc** [comment]
Why exactly does this project need a different name to signal it's not supported by the core cpython maintainers (or that it's an one-man show)? Whom exactly would be confused by a similar name? Doesn't seem so "confusing" to me - the cpython maintainers made it very clear that they don't want to maintain python2, no surprise a 3rd party would make a 2.8.

I'm asking from a practical perspective here. A different name would make this project annoying to use, from a packaging/installing perspective at least, and probably derail it with endless debates about a different name.

**Comment by henrebotha** [comment]
@ionelmc It should be obvious. Someone fairly new to the Python ecosystem, or someone who prefers to avoid language politics, would very, very easily assume something named "Python 2.8" is, in fact, version 2.8 of Python.

**Comment by stefantalpalaru** [comment]
@ionelmc, it's a political issue. Python's core devs have been trying for the last 8 years to convince, cajole and arm-twist their user base into switching to a backwards incompatible (and for a long time slower) version of the main implementation.

For all intents and purposes, this new version is implementing a different language, judging by the effort needed to port Python 2 code to Python 3. Most of us said that if we were to do such an effort, we might as well port it to a more efficient programming language.

Since people insisted on sticking to Python 2, or silently migrated to Go/Rust/Nim/etc., the core devs doubled down on their attempts to kill Python 2 - perceived as the major obstacle in Python 3's adoption.

What you're seeing right now is just the latest of these actions - a rather pathetic attempt to cripple a fork that's breathing new life into Python 2 by denying it a name that makes sense.

The same entity that grants free use of the "Python" trademark in "IronPyton" and "wxPython" is suddenly lawyering up to fight "py" followed by one or more digits. It's ridiculous.

Now, I understand that @naftaliharris wants this to be a friendly fork and stay on good relations with the core devs, but it's not possible. He started the conflict by reviving that which should have been dead or at least dying. The only name that makes Guido and his cheerleaders happy is one that's as remote from Python as possible, in order to interfere with the fork's adoption.

**Comment by kirbyfan64** [comment]
Wow, you must love your totally ridiculous conspiracy theories. The thing that really got me, though, was:

> The only name that makes Guido and his cheerleaders happy is one that's as remote from Python as possible, in order to interfere with the fork's adoption.

Come on, I'm a Python 2 user and I even see this is ridiculous. Someone isn't going to be like, "Hey, I'm going to google Python 2.8, because I just know that there'll be a Python fork there!!" They don't. The name would hardly "hinder" adoption.

**Comment by ionelmc** [comment]
But does anyone really want a 2.8 from a 3rd party? Seriously now, isn't the very existence, or perhaps the success of such a project proof that the core team failed to meet the needs of the users? Perhaps there should be talk about what changes Python 3 should have to meet said needs ...

Also, @henrebotha, your argument assumes that for some reason there cannot ever be a 2.8 and thus, this project cannot have that name because then newbies will think 2.8 exists. I'm not sure what to make of it ...

**Comment by flying-sheep** [comment]
~~maybe~~ we should not derail this thread.

please stick to the topic.

**Comment by ecesena** [comment]
I don't mean to troll here, but I don't understand why calling *the repo* python28 is bad -- the code is still full of the word Python in all docs, comments, etc.

I was looking for this repo to stay up to date, and it was really hard to find "placeholder".
Please rename it to unofficial-python28 if you want to stress that it's unofficial, but please help people like me finding the project.

**Comment by flying-sheep** [comment]
“placeholder” is just a… placeholder. i’m assuming @naftaliharris will decide on a name in the coming days.

**Comment by paul-nechifor** [comment]
In the spirit of Cython and Jython how about:

 - **Aython**: The positive Python. Aye!
 - **Bython**: A Python **by** someone who likes backwards compatibility.
 - ~~Cython~~: Taken.
 - **Dython**: A Python to die for.
 - **Eython**: A Python that increments to two point "eyt".
 - **Fython**: Fight for a backwards compatible version of Python.
 - **Gython**
 - **Hython**
 - **Iython**
 - ~~Jython~~: Taken.
 - **Kython**
 - **Lython**
 - **Mython**: A python that will run **my** old code too.
 - **Nython**: It's **N**ot incompatible with Python 2.
 - **Oython**
 - ~~Python~~: No touching!
 - **Qython**: It's quite Python like.
 - **Rython**: The right type of Python.
 - **Sython**
 - **Tython**
 - **Uython**
 - **Vython**: The Python vying to succeed Python 2
 - **Wython**
 - **Xython**
 - **Yython**
 - **Zython**

**Comment by ma8ma** [comment]
How about **Back2Python** (`/usr/bin/b2py` or `/usr/bin/b2python`)?
It means Python 3 features back to Python 2, and similar to my favorite movie title too 😄

**Comment by naftaliharris** [comment]
I'm so impressed with the quality of names here. You all should work in marketing. ;-)

Pyvergent, Mython, and Placeholder are my favorites. @vanl, I presume all of those work for you?

"snek" makes me laugh but I don't think I'd be able to take the project seriously that way. Reminds me of PythonyMcPyface. I liked "pythonesque/pesque" but then realized that "pesque" sounds the same as "pesk" which is not the point of this project.

Sorry by the way that picking a name is taking me a little bit; I'm traveling through the 19th so am not totally focused on this, and naming is really really important... Very excited to pick one and move past this.

> A different name would make this project annoying to use, from a packaging/installing perspective at least,
> The name would hardly "hinder" adoption.

The primary feature of this project is backwards compatibility with 2.7 code, so I obviously don't want to anything that breaks that. Now, I don't know much about packaging yet--I have a lot of unknown unknowns there currently--but it seems to me that for example pypy's ability to serve as a drop-in replacement for CPython has not been hurt by the fact that its name isn't "python".

**Comment by ncoghlan** [comment]
Just a note that Mython already exists: http://mython.org/

**Comment by stefantalpalaru** [comment]
> pypy's ability to serve as a drop-in replacement for CPython

It's not there, yet. The Python Package Index has [26441 packages supporting CPython 2.7](https://pypi.python.org/pypi?:action=browse&c=532) and only [2659 supporting PyPy](https://pypi.python.org/pypi?:action=browse&c=554).

**Comment by AndrewBelt** [comment]
Not to add to the naming spam, as this part of the discussion should take place in a chatroom, but there are tons of good ones in here. https://en.wikipedia.org/wiki/List_of_snakes_by_common_name

**Comment by petsuter** [comment]
* [Zompy](https://en.wikipedia.org/wiki/Zombie)
* [Pynocchio](https://en.wikipedia.org/wiki/Pinocchio)
* [The Curious Case of Benjamin Pytton](https://en.wikipedia.org/wiki/The_Curious_Case_of_Benjamin_Button_(film))
*  [Don't mention the war 2.8](https://en.wikiquote.org/wiki/Fawlty_Towers#The_Germans)
* [Foreverpyoung](https://en.wikipedia.org/wiki/Forever_Young)
* [Pyouroboros](https://en.wikipedia.org/wiki/Ouroboros)

**Comment by wannaphongcom** [comment]
nextpy

**Comment by sandys** [comment]
molurus or bivittatus - latin name of the great indian or burmese python.

FYI molurus.org is also available.  so is bivittatus.com 

bivittatus - doesnt it sound like two and eight ?

**Comment by manojpandey** [comment]
As @ma8ma points out:

How about `backpy` ?
###### make python great again.

**Comment by denysvitali** [comment]
Name it pIton lol

**Comment by obestwalter** [comment]
@naftaliharris - well, this is fun - so here's my suggestion :)

What if you can have all the letters from Python without having to name it Python? What if you can even have the snake reference in the name (with a little associative jump)? 

So here goes: do you remember Kaa from the jungle book? Kaa is a giant **Python** that **hypnot**izes Mogli. So just call it

### Hypnot

... and be done with it.

BTW: this would be pronounced like *hype-not*

**Comment by ecesena** [comment]
@obestwalter and great anagram too 👍

**Comment by ei-grad** [comment]
Why not `pep404`?

**Comment by sibayanjasper** [comment]
I suggest
* `dpy` - **D**iscontinued python
* `opy` - **O**verhauled python
* `vyper` - "viper" another snake but with "y" for familiarity

**Comment by chainsawriot** [comment]
Python 2.8 is not okay then just call it `twoeight`.

**Comment by alanjds** [comment]
I would like to adopt Py3 if it does not break my Py2 code. The 2to3 tool is less helpful than a 3to2 one. What I dream is a way to code 3 along with existing 2. Backport and derived is what sticks on my mind, but the ideas of merged, along, bridge and feasible gives me future-related smiles. 

MergedPython
AlongPython 
AlonguedPython (longer Py2 snake life) 
BackFromFuturePy (bffpython2.8 is a ready joke)
BackToTheFuturePy (ok. This is a bad one)
NewOldPython (for now on, no p0rn-related names)

The ideas or this being what we want but not what PSF want are still fresh 

LostPython
DeprecatedPython
UnwantedPython
WantedPython (we want alive, they want dead)
DissidentPython

But to be really fair, this would be a short-lived necessity until something else cames, like a yet to be written bytecode transpiler got wrote

PythonSkin (only the past echo of a new snake)
YetwoPython
NothreePython

And to finish, I liked backpy until a remind of Trump and old and new clashing and hate and flames. I want to see a future good for both people. A future where the same BothPython runs Python2 unmodified code for py2 people and Python3 unmodified code for py3 people.

BothPython !

**Comment by Bl41r** [comment]
Has Crython been taken?

**Comment by senyai** [comment]
You all guys know 'the Knights who say "Ni!"', right? Guess what the element number of Ni is in periodic table? 28! So let's say Ni! to python 3, and run nipyton.

**Comment by ei-grad** [comment]
It also means "neither" in ukranian.

**Comment by conradsnicta** [comment]
@naftaliharris - Nice and useful project :)  Some suggestions for the name, which would send a clear message: it's close to Python without being the so-called "official" Python:  
- `pithon`
- `piethon`
- `bython`
- `repy28` or simply `repy` (where the `re` is for retro)

**Comment by mirabilos** [comment]
Nothing with `py` in it, that’s already mostly used by packages *for* Python.

“Pyesque” (even “pesque”) is very hard to pronounce for Germans (for example); I’d not have such objections with “snek” (which also made me laugh).

Please recherche in Debian unstable beforehand whether the name is taken by **any** package, as otherwise, Debian will not allow it in unrenamed (node.js was renamed from node to nodejs because “node” was taken by an Amateur Radio program widely deployed in remote locations and over a decade older, for example).

**Comment by naftaliharris** [comment]
> Please recherche in Debian unstable beforehand whether the name is taken by any package, as otherwise, Debian will not allow it in unrenamed

Thanks for that!

**Comment by miraculixx** [comment]
@gvanrossum the world has an abundance of "technically superior" projects that went nowhere... wat we need is solutions that work, and this project is clearly on the right track. yea

**Comment by elkarouh** [comment]
Name suggestion: **Python2++**

**Comment by RecklessProcedure** [comment]
I'm all for this. I despise Python3 for a number of reasons. Ever have a reason to compile Python from scratch? When you try to build Python3: "Error: G++ required" "Test suite must be run from an xterminal". So much for a system with only cross-compiled C and/or anyone running without Xorg. Such nonsense decisions by the Py3 team, the worst of which was a decision to re-implement rather than extend in more Unicode friendly ways. Shovel the work onto your users.

**Anyway, about the name: Typhon is an anagram of the name. Thypon is another, with a slightly Monte sound.**

**Comment by tiran** [comment]
Well, this discussion hit rock bottom with fake news and false accusations.

**Comment by pfalcon** [comment]
Also, stats: during the last month (which generally should be prolific at least in the number of people poked with it, due to holidays), 3 people contributed commits, 23 the maintainer and 2 other people contributed a commit each. So, importance and usefulness of this project seems to be overrated. This is a cute pet project for @naftaliharris , and he can be only wished best of luck with it, and so far he chose the right name for the project: "placeholder" is confusing, but the whole project is confusing, so naming is on par.

**Comment by kirbyfan64** [comment]
@tiran

> Well, this discussion hit rock bottom with fake news and false accusations.

Words of truth right there...

**Comment by alanjds** [comment]
A placeholder between Python 2 and Python 3 is nice for me. Just have no clue that it is a Python-related thing.

plyceholder ?

**Comment by RecklessProcedure** [comment]
As to fake news and false accusations: All of that I see is people coming here to make some kind of trouble or discouraging remark about someone trying to keep 2.x alive. What motivates them is irrelevant, conspiracy or not. But, as much as I'd like to see 2.x keep going, I largely do not care. Why? Because the 2/3 debacle has caused me no small amount of trouble. As such, I've ruled the language out as a whole for anything but small scripts going forward and... I'm not the only one to do so.

**Comment by kirbyfan64** [comment]
I'm going to humbly suggest that @naftaliharris lock this issue, because at this point it's mostly people suggesting random names (too many to search through) or people yelling "omg python three suxx" or "omg dis project is stuupidz" or other random crap...

**Comment by pfalcon** [comment]
> someone trying to keep 2.x alive

The Python release team keeps 2.x alive. They do that for 16 years. Nobody was able to beat them at that so far. Only 2.7.x series is kept alive for 6 years, with current release being 2.7.13.

> I'm not the only one to do so.

You aren't. But everyone else either keeps using 2.x or have switched to 3.x over last 9 years. (Supporting both ain't rocket science either, though with Python3 being available for long time everywhere, there's little point to do so for new projects.) And there's hard to talk about discouragement of projects like this - Python community has always been, and always will be prolific - it's not like other languages, where there's barely a couple of implementations. Stackless Python, Unladen Swallow, Nuitka, PyPy, Pyston, Grumpy, and many of others, including bunch to come. It's just matter of fact that some of these implementations are used less than others, and some even get abandoned.

**Comment by hadrianw** [comment]
Name proposal: February Python (as it is between 27 and 30 having only 28 or 29 days)

Variations: pyfebruary, Eternal February (eterfeb), Fybruar, February Edition

But placholder is nice as it is.

Disclaimer: I do not have horses in this race.

**Comment by dhj-io** [comment]
My favorites so far --

nipy : Ni Python (from @senyai )
zython : The last py you'll need (from @paul-nechifor )
pystasis, pyfrost : good indication of support for fixes with no breaking changes (from @ncoghlan )
monty : great one for obvious reasons.  maybe the student project would be cool with it (from @ojn )
pyclassic : reminiscent of when coca-cola fixed their mistake.

**Comment by mvasilkov** [comment]
I kinda like the name Placeholder.

As for the binaries, they can be e.g. prefixed with p: /usr/local/bin/ppython

**Comment by sergey-salnikov** [comment]
Ex-Ex-Parrot (/usr/bin/xxp)?

**Comment by ojn** [comment]
As @ncoghlan mentioned, asciipy describes the project nicely. PSF would probably also allow asciiPython name since it's clear that it is a different python implementation.

**Comment by omeid** [comment]
`bython` as in, Backported Python?

**Comment by mirabilos** [comment]
Nothing with py- or alluring to python, to avoid confusion.

**Comment by stefantalpalaru** [comment]
When you decide on a name, this should help you find the places that need to be edited: https://github.com/stefantalpalaru/gentoo-overlay/blob/master/dev-lang/py28/files/py28-rename.patch

Some "python2.8" symlinks are needed so existing autotools setups work unmodified, but that's more of a distro packager issue. On Gentoo I'm getting away with only:

```
/usr/lib64/python2.8
/usr/lib64/libpython2.8.a
/usr/lib64/libpython2.8.so
```

**Comment by denysvitali** [comment]
To be honest, I quite like "placeholder" as a name

**Comment by sibayanjasper** [comment]
>I suggest
>* `dpy` - **D**iscontinued python
>* `opy` - **O**verhauled python (sounds like o-pie)
>* `vyper` - "viper" another snake but with "y" for familiarity
* `senpy` - notice me
* `pynest`

**Comment by dhj-io** [comment]
vyper.  YES.

**Comment by omidraha** [comment]
`py2020` (The End Of Life date for Python 2.7)

**Comment by hashbackup** [comment]
Suggestion: py

It's short & obviously not a trademark infringement on Python

**Comment by perennialmind** [comment]
I know placeholder is py 2.x, not pi × 2, but what about `tauthon` in the spirit of the [Tau Manifesto](https://www.tauday.com/)? It's cheeky and fits the contrarian viewpoint.

**Comment by mrabarnett** [comment]
"py" is already used by Python as a launcher.

**Comment by naftaliharris** [comment]
> I know placeholder is py 2.x, not pi × 2, but what about tauthon in the spirit of the Tau Manifesto?

Perfect perfect PERFECT! :-D

* 6.28: six, like the six module. 28, as in PEP 404.
* pi -> tau, like e.g. C -> C++
* Two syllables, easy to say.
* Domain name is open, (though not anymore!)
* No debian packages of the same name.
* No other projects of the same name
* Obviously not an official python release.
* "It's cheeky and fits the contrarian viewpoint."

"tauthon" is the new and permanent name of this project.

Thanks @perennialmind!

**Comment by naftaliharris** [comment]
Thanks a lot to everyone who suggested names--they were uniformly better than my ideas. You're all a lot more talented than me at this, apparently. :-)

Next up, PR to change the name!

**Comment by ncoghlan** [comment]
math.tau just landed in 3.6 as well :)

Very cool idea @perennialmind, and thanks once again for being such a good sport about finding a new name, @naftaliharris!

**Comment by naftaliharris** [comment]
> math.tau just landed in 3.6 as well :)

Ha, well tauthon definitely has to have this too!

> thanks once again for being such a good sport about finding a new name, @naftaliharris!

Of course. :-)

@ncoghlan, I have a small patch for a minor traceback bug in 2.7 I wanted to contribute upstream. http://bugs.python.org/issue29107 Any advice on getting a review? Just ping the watchers again?

**Comment by Juronski** [comment]
@gvanrossum
> OK, bring in the lawyers.

Thank you Guido van Rossum for your arguments. I would like to draw your attention to the fact that the EOL of Python 2.7 is seen as fraud. It is even experienced as a kind of extortion. Do or die. Read about the Python 2 EOL-scam at this discussion:  https://community.plone.org/t/pre-discussion-on-plip-maintain-py2-support/11383/41

**Comment by flying-sheep** [comment]
This discussion is over, the project has been renamed. @naftaliharris can you please lock this to avoid spam like the above?

**Comment by Juronski** [comment]
@flying-sheep my post was not addressed to you. Sheeps always will be sheeps.

**Comment by naftaliharris** [comment]
Locked, we changed this a long time ago. And +1 for civility.
